sudo: false
language: python

services:
  - postgresql

addons:
  postgresql: "9.6"

install:
  - travis_retry pip install tox tox-travis

script:
  - tox

matrix:
  fast_finish: true
  include:
    # https://docs.djangoproject.com/en/dev/faq/install/#what-python-version-can-i-use-with-django
    - {env: DJANGO=3.2, python: '3.6'}
    - {env: DJANGO=3.2, python: '3.7'}
    - {env: DJANGO=3.2, python: '3.8'}
    - {env: DJANGO=3.2, python: '3.9'}
    - {env: DJANGO=3.2, python: 'nightly'}

    - {env: DJANGO=master, python: '3.6'}
    - {env: DJANGO=master, python: '3.7'}
    - {env: DJANGO=master, python: '3.8'}
    - {env: DJANGO=master, python: '3.9'}
    - {env: DJANGO=master, python: 'nightly'}

    - {python: '3.9', env: TOXENV=docstring}
    - {python: '3.9', env: TOXENV=quality}

  allow_failures:
    - python: 'nightly'
    - env: DJANGO=master
